### PR TITLE
reduced compressed video

### PR DESCRIPTION
**Pull request by ccznn**
Due to long loading times of zenon.network, I've downloaded dna.json, converted it to mp4, compressed it using ffmpeg, converted it to lottie file again, now it is 5.8mb. It could be less than this but I wanted to use 120 frames.

I couldn't test the website.

### CODE REVIEW

**Comment by 0x3639** [comment]
This is the rendering in question

Current Rendering Quality
image

Proposed Quality
image

**Comment by ccznn** [comment]
I've used 65 percent quality to decrease file size, but I can close if it's so low

**Comment by 0x3639** [comment]
Here is what the mp4 looks like.  If we like this I can work on getting rid of that watermark.

https://github.com/zenon-network/zenon.network/assets/5406130/202edd88-bb09-4179-851a-431863da0de6

**Comment by ccznn** [comment]
I think mp4 one plays smoother than lootie, it's smoother on my m1 macbook air. I think using mp4 will be better

**Comment by 0x3639** [comment]
> I think mp4 one plays smoother than lootie, it's smoother on my m1 macbook air. I think using mp4 will be better

I wonder if an mp4 will be possible.  The mp4 would need to loop continuously and we would need to perfectly time the stoping port with the starting point.  

Will that even be possible?

**Pull request closed without merging**
